### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by AlexandraOM** [oliverjam/learn-form-validation#1]
in the browse: users > in the browser: users

asterix = ![](https://media.giphy.com/media/1Md9azxcgIyQ/giphy.gif)
asterisk = *

https://github.com/oliverjam/learn-form-validation#challenge-1
Add a required indicator to both inputs. 
Change to : 
Add a visual indicator to both inputs

**Comment by AlexandraOM** [comment]
https://github.com/oliverjam/learn-form-validation#different-types-of-value
We can just put a <div> after the label, but this won't be associated with the input (which means screen readers will ignore it). The aria-describedby attribute is used to provide descriptive information about an element: you provide it with one or more IDs of elements that describe this one.

Change to: 

We can add a ```<div>``` with more information after the label but this won’t automatically be associated with the input (which means screen readers will ignore it).
To link the description to the input use the
```aria-describedby=```  attribute for the element you are describing and link it to the id of the description.

**Comment by oliverjam** [comment]
Thanks! Didn't do a PR but this was fixed in the last couple of commits

https://github.com/oliverjam/learn-form-validation/commit/ed604b66e9bcc9519d316eb2dca3a39413c213b6
https://github.com/oliverjam/learn-form-validation/commit/0231011bdce9df103e52b778b8f227411be7e2b0
https://github.com/oliverjam/learn-form-validation/commit/168970a42da3b5f00064227d965dab24d0de0ad2
https://github.com/oliverjam/learn-form-validation/commit/20db778cd8bdd2c769ac34bc62f087d5fba1bee2
